# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provision :shell, path: "provisioning.sh"
  config.vm.provision :shell, path: "StartUp.sh", run: "always"
end
