# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utarena', '0002_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('team', models.IntegerField(choices=[(1, 'Red'), (2, 'Blue')], null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utarena.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utarena.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.ManyToManyField(related_name='joined_games', through='utarena.PlayerGame', to='utarena.Game'),
        ),
        migrations.AlterUniqueTogether(
            name='playergame',
            unique_together=set([('player', 'game')]),
        ),
    ]
