---
- hosts: servers
  vars_files:
    - vars.yml
  gather_facts: false
  user: "{{ user }}"

  tasks:
    - name: Update apt cache
      become: yes
      become_method: sudo
      apt: update-cache=yes

    - name: Install system packages
      become: yes
      become_method: sudo
      apt: pkg={{ item }}
      with_items: "{{ system_packages }}"

    - name: disable nginx
      become: yes
      become_method: sudo
      shell: "update-rc.d -f nginx disable"

    - name: stop nginx
      service: name=nginx state=stopped

    - name: Create temp directory for app
      file: path={{ temp_dir }} state=directory owner={{ user }}

    - name: Create directory for app
      become: yes
      become_method: sudo
      file: path={{ app_home }} state=directory owner={{ user }}

    - name: Create directory for logs
      become: yes
      become_method: sudo
      file: path=/var/log/ut-arena state=directory owner={{ user }}

    - name: make sure postgresql server is running
      service: name=postgresql state=started

    - name: Create a database
      become: yes
      become_method: sudo
      become_user: postgres
      postgresql_db: name={{ db_name }}

    - name: Create a database user
      become: yes
      become_method: sudo
      become_user: postgres
      postgresql_user: db={{ db_name }} name={{ db_user }} password={{ db_password }} priv=ALL

- include: deploy.yml
