# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34550db0cabafb5fa1990c6923f358cccd02b80e0c288eabb4213cf070a50887a19111018e13e5b6ea9f405a9d5b8530ef8418e78dd0d882354463b4be0563d4

test:
  secret_key_base: 8908e5a55ce7b2ed38b835c973b36e7cbbb37353092ecc86386cb27a460e25cf0097f4313fa51499580334851781c517e7f7de5aec46807266bf92ca45fb9f01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
